---
title: "LI water temps 2019"
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'index.html'))})
author: "A. Starke"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
library(plotly)
library(tidyverse)
library(dplyr)
library(magrittr)

library(chron)
library(lubridate)
library(stringr)
library(tsibble)
library(xts)
library(lubridate)
library(dataRetrieval)

# plotting tools
library(ggplot2)
library(ggthemes)
library(ggExtra)
library(scales)
library(hrbrthemes)
# Spatial packages

library(sf)
library(maptools)
library(RColorBrewer)
library(mapview)
library(knitr)
library(rmarkdown)

library(weatherData)
library(lunar)



```

## Water temperature stations

Exploring temperature data in the Peconics.
2 USGS guage stations exist with continuous data collection. 


```{r sites}
# estuarySites <- whatNWISsites(stateCd = "NY", 
#               # water temp C
#               parameterCd = "00010") %>% 
#   filter(site_tp_cd == "ES") %>% 
#   pull(site_no)

peconicSiteIDs <- c("01304200", "01304562")

dailyTemps <- readNWISdv(siteNumbers = peconicSiteIDs, 
                         startDate = "2013-01-01", #first full year of data collection 2013.
                         endDate = "2019-11-01",
                         statCd = c("00001", "00002", "00003"),
                         parameterCd = "00010") %>% 
  dataRetrieval::renameNWISColumns() 

dailyTemps <- dailyTemps %>% filter(Wtemp < 100 & Wtemp > -10) # filter out coded -9999s and 9999s


estuarySiteLocations <- readNWISsite(peconicSiteIDs) %>% 
  st_as_sf(coords = c("dec_long_va", "dec_lat_va"), crs = 4269)

mapview(estuarySiteLocations)


```

## Plots
 
Data has been collected since 2012, with 2013 being the first 'full' year of data collection.


```{r temps, echo=FALSE}
# go tsibble.
theme_set(theme_ipsum())

temps <- dailyTemps %>% 
  # join to get station names
  left_join(estuarySiteLocations %>% 
              select(site_no, station_nm)) %>%
   as_tsibble(key = station_nm, index = Date) %>% 
  fill_gaps() %>% 
  mutate(month = month(Date),
         year = year(Date),
         day_of_year = yday(Date),
         commonDate = as.Date(paste0("2000-",format(Date, "%j")), "%Y-%j"))

 


temps  %>% 
  ggplot(aes(x = commonDate, y = Wtemp, color = Wtemp, group = year)) +
  geom_line() + 
  # scale_color_gradient(low = "blue", high = "red", aesthetics = "color") + 
  scale_color_viridis_c(option = "inferno") +
  facet_grid(station_nm ~ year) + 
  scale_x_date(labels = function(x) format(x, "%d-%b")) +
  # scale_x_continuous(labels = function(x) format(as.Date(as.character(x), "%j"), "%d-%b")) +
  theme(legend.position = "none", axis.text.x = element_text(angle = 90, hjust = 1)) + 
  labs(y = "Temp (c)", x = NULL)


```

## Anomolies?  
How do the temps of 2019 compare with the past? 
Red ribbon = 2019 temperature range based on daily statistics
 
```{r anomolies, message=FALSE, warning=FALSE, paged.print=FALSE}
daily_mean_7yr <- temps %>% 
  # filter to get 2012-2018
  filter(year != 2019) %>% 
  # group by site (site is key)
  group_by_key() %>%
  # index by the day of year
  index_by(day_of_year = ~ yday(.)) %>% 
  summarize(temp_mean7yr = mean(Wtemp, na.rm = TRUE),
            temp_max7yr = mean(Wtemp_Max, na.rm = TRUE),
            temp_min7yr = mean(Wtemp_Min, na.rm = TRUE))

daily_mean_7yr %>% ggplot(aes(x = day_of_year, y = temp_mean7yr)) + 
  geom_ribbon(aes(ymax = temp_max7yr, ymin = temp_min7yr), alpha = 0.6) +
  # geom_line(aes(y = temp_min7yr)) +
  # geom_line(aes(y = temp_max7yr)) + 
  geom_ribbon(data = temps %>% filter(year == 2019), 
              aes(y = Wtemp, ymin = Wtemp_Min, ymax = Wtemp_Max), fill = 'red', alpha = 0.6) + 
  # theme_minimal() + 
  scale_x_continuous(labels = function(x) format(as.Date(as.character(x), "%j"), "%d-%b")) +
  # scale_x_date(labels = function(x) format(x, "%d-%b")) +
  facet_grid(station_nm ~ .) + 
  labs(main = "2019 Daily temperatures compared to 6 year means (2013-2018)", 
       x = "Date")


```

